server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123

  main:
      allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        show_sql: true
    database: postgresql
jwt:
  token:
    secret: jwtcleeancode
    validity: 864000000
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    tryItOutEnabled: true
    path: swagger-ui
    csrf:
      enabled: true



